In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

import json
from bs4 import BeautifulSoup
from urllib.request import urlopen

import warnings
warnings.filterwarnings('ignore')

In [2]:
mix = pd.read_csv('./new_mix.csv')

In [3]:
mix

,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,Min,...,Launch1,AvgLen,Launch111,AvgLen11,Opp,Stp,Stp1,OPA,OPA90,AvgDist
0,Max Aarons,eng ENG,DF,Norwich,Premier League,22,2000.0,29,27,2431,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Yunis Abdelhamid,ma MAR,DF,Reims,Ligue 1,34,1987.0,29,29,2533,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Salis Abdul Samed,gh GHA,MF,Clermont_Foot,Ligue 1,22,2000.0,28,27,2308,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Laurent Abergel,fr FRA,MF,Lorient,Ligue 1,29,1993.0,29,29,2536,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Charles Abi,fr FRA,FW,Saint-Etienne,Ligue 1,22,2000.0,1,1,45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2844,Guglielmo Vicario,it ITA,GK,Empoli,Serie A,25,1996.0,33,33,2970,...,30.1,31.9,47.6,40.5,338.0,30.0,8.9,16.0,0.48,13.1
2845,Freddie Woodman,eng ENG,GK,Newcastle_United,Premier League,25,1997.0,4,4,360,...,53.8,43.3,65.1,52.0,33.0,2.0,6.1,0.0,0.00,11.6
2846,Robin Zentner,de GER,GK,Mainz_05,Bundesliga,27,1994.0,31,31,2790,...,41.0,37.9,49.4,43.3,242.0,23.0,9.5,47.0,1.52,17.3
2847,Luca Zidane,fr FRA,GK,Rayo_Vallecano,La Liga,23,1998.0,7,7,555,...,42.6,38.1,63.0,50.0,49.0,4.0,8.2,2.0,0.32,12.4
2848,Jeroen Zoet,nl NED,GK,Spezia,Serie A,31,1991.0,7,7,630,...,32.0,33.9,42.6,39.4,52.0,3.0,5.8,5.0,0.71,13.7

In [4]:
clubname = 'Real_Madrid'

In [5]:
s = mix[mix['Squad'] == clubname]

In [6]:
s

,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,Min,...,Launch1,AvgLen,Launch111,AvgLen11,Opp,Stp,Stp1,OPA,OPA90,AvgDist
44,David Alaba,at AUT,DF,Real_Madrid,La Liga,29,1992.0,30,30,2642,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122,Marco Asensio,es ESP,FW,Real_Madrid,La Liga,26,1996.0,28,16,1461,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
168,Gareth Bale,wls WAL,FW,Real_Madrid,La Liga,32,1989.0,5,4,280,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
262,Karim Benzema,fr FRA,FW,Real_Madrid,La Liga,34,1987.0,29,29,2398,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
292,Blanco,es ESP,MF,Real_Madrid,La Liga,21,2000.0,1,0,31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
403,Eduardo Camavinga,fr FRA,MF,Real_Madrid,La Liga,19,2002.0,21,9,892,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
432,Dani Carvajal,es ESP,DF,Real_Madrid,La Liga,30,1992.0,22,16,1434,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
435,Casemiro,br BRA,MF,Real_Madrid,La Liga,30,1992.0,28,27,2314,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
449,Dani Ceballos,es ESP,MF,Real_Madrid,La Liga,25,1996.0,8,1,138,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
944,Peter González,do DOM,DF,Real_Madrid,La Liga,19,2002.0,2,0,11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1011,Miguel Gutiérrez,es ESP,DF,Real_Madrid,La Liga,20,2001.0,3,3,260,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1043,Eden Hazard,be BEL,FW,Real_Madrid,La Liga,31,1991.0,17,7,690,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1138,Isco,es ESP,MF,Real_Madrid,La Liga,30,1992.0,11,2,216,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1196,Luka Jović,rs SRB,FW,Real_Madrid,La Liga,24,1997.0,13,0,293,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1204,Vinicius Júnior,br BRA,FW,Real_Madrid,La Liga,21,2000.0,31,28,2464,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1318,Toni Kroos,de GER,MF,Real_Madrid,La Liga,32,1990.0,23,22,1854,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1511,Marcelo,br BRA,DF,Real_Madrid,La Liga,33,1988.0,9,3,331,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1523,Mariano,do DOM,FW,Real_Madrid,La Liga,28,1993.0,6,1,173,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1611,Ferland Mendy,fr FRA,DF,Real_Madrid,La Liga,26,1995.0,19,18,1552,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1638,Éder Militão,br BRA,DF,Real_Madrid,La Liga,24,1998.0,31,31,2784,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1661,Luka Modrić,hr CRO,MF,Real_Madrid,La Liga,36,1985.0,24,22,1807,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1732,Nacho,es ESP,DF,Real_Madrid,La Liga,32,1990.0,24,13,1204,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2084,Rodrygo,br BRA,FW,Real_Madrid,La Liga,21,2001.0,27,11,1102,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2177,Sergio Santos,es ESP,DF,Real_Madrid,La Liga,21,2001.0,1,0,11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2485,Jesús Vallejo,es ESP,DF,Real_Madrid,La Liga,25,1997.0,1,0,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2488,Federico Valverde,uy URU,MF,Real_Madrid,La Liga,23,1998.0,27,17,1621,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2501,Lucas Vázquez,es ESP,DF,Real_Madrid,La Liga,30,1991.0,25,16,1473,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2688,Thibaut Courtois,be BEL,GK,Real_Madrid,La Liga,29,1992.0,33,33,2970,...,24.5,31.8,44.8,40.6,289.0,26.0,9.0,21.0,0.64,14.4

In [7]:
s.describe()

,Born,MP,Starts,Min,90s,Gls,Ast,GPK,PK,PKatt,...,Launch1,AvgLen,Launch111,AvgLen11,Opp,Stp,Stp1,OPA,OPA90,AvgDist
count,28.000000,28.000000,28.000000,28.000000,28.000000,28.000000,28.000000,28.000000,28.000000,28.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.00,1.0
mean,1994.571429,17.821429,12.821429,1157.642857,12.857143,2.464286,1.750000,2.178571,0.285714,0.535714,...,24.5,31.8,44.8,40.6,289.0,26.0,9.0,21.0,0.64,14.4
std,4.939850,11.018683,11.401928,975.207223,10.836954,5.343616,2.605194,4.320953,1.329359,2.134065,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1985.000000,1.000000,0.000000,8.000000,0.100000,0.000000,0.000000,0.000000,0.000000,0.000000,...,24.5,31.8,44.8,40.6,289.0,26.0,9.0,21.0,0.64,14.4
25%,1991.000000,7.500000,1.750000,249.000000,2.775000,0.000000,0.000000,0.000000,0.000000,0.000000,...,24.5,31.8,44.8,40.6,289.0,26.0,9.0,21.0,0.64,14.4
50%,1994.000000,21.500000,12.000000,1153.000000,12.800000,1.000000,1.000000,1.000000,0.000000,0.000000,...,24.5,31.8,44.8,40.6,289.0,26.0,9.0,21.0,0.64,14.4
75%,1998.500000,27.250000,22.000000,1818.750000,20.225000,2.000000,3.000000,1.250000,0.000000,0.000000,...,24.5,31.8,44.8,40.6,289.0,26.0,9.0,21.0,0.64,14.4
max,2002.000000,33.000000,33.000000,2970.000000,33.000000,25.000000,11.000000,18.000000,7.000000,11.000000,...,24.5,31.8,44.8,40.6,289.0,26.0,9.0,21.0,0.64,14.4

In [8]:
df = s.copy()
df1 = df.iloc[:, :10]
df2 = df.iloc[:, 11:]
df2 = df2.fillna(0)

In [9]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 28 entries, 44 to 2688
Columns: 160 entries, Gls to AvgDist
dtypes: float64(148), int64(12)
memory usage: 35.2 KB

In [10]:
normalized_df2=(df2-df2.min())/(df2.max()-df2.min())

In [11]:
normalized_df2.describe()

,Gls,Ast,GPK,PK,PKatt,CrdY,CrdR,Gls1,Ast1,GA,...,Launch1,AvgLen,Launch111,AvgLen11,Opp,Stp,Stp1,OPA,OPA90,AvgDist
count,28.000000,28.000000,28.000000,28.000000,28.000000,28.000000,0.0,28.000000,28.000000,28.000000,...,28.000000,28.000000,28.000000,28.000000,28.000000,28.000000,28.000000,28.000000,28.000000,28.000000
mean,0.098571,0.159091,0.121032,0.040816,0.048701,0.235714,NaN,0.157295,0.223653,0.210582,...,0.035714,0.035714,0.035714,0.035714,0.035714,0.035714,0.035714,0.035714,0.035714,0.035714
std,0.213745,0.236836,0.240053,0.189908,0.194006,0.248274,NaN,0.239046,0.283002,0.231770,...,0.188982,0.188982,0.188982,0.188982,0.188982,0.188982,0.188982,0.188982,0.188982,0.188982
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.075000,NaN,0.000000,0.000000,0.066667,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.040000,0.090909,0.055556,0.000000,0.000000,0.200000,NaN,0.058511,0.098361,0.144444,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.080000,0.272727,0.069444,0.000000,0.000000,0.400000,NaN,0.218085,0.409836,0.259259,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,NaN,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [12]:
normalized_df = pd.concat([df1, normalized_df2], axis=1)

In [13]:
a = 3
b = 2
c = 1
d = -1
e = -2
f = -3

In [14]:
df = normalized_df.copy()

In [15]:
df['goalkeeper'] = (f*normalized_df.GA90 + b*normalized_df.Save1 + b*normalized_df.W + c*normalized_df.D 
              + d*normalized_df.L + a*normalized_df.Save1 + e*normalized_df.PSxG1 + b*normalized_df.Cmp 
              + c*normalized_df.Stp1 + b*normalized_df.OPA90) / (2*a + 5*b + 3*c)

df['defender'] = (c*normalized_df.Gls + b*normalized_df.Ast + e*normalized_df.CrdY + f*normalized_df.CrdR 
            + c*normalized_df.Cmp1 + f*normalized_df.Err + f*normalized_df.CrdY2 + b*normalized_df.Fls
            + b*normalized_df.PrgDist + c*normalized_df.KP + c*normalized_df.Recov
            + c*normalized_df.CrsPA + c*normalized_df.SCA90 + c*normalized_df.GCA90 + b*normalized_df.TklW
            + b*normalized_df.Tkl1 + f*normalized_df.Past + c*normalized_df.Succ1
            + f*normalized_df.PKcon + c*normalized_df.Won1) / (5*a + 6*b + 9*c)

df['forward'] = (c*normalized_df.Gls + b*normalized_df.Ast + e*normalized_df.CrdY + f*normalized_df.CrdR 
           + b*normalized_df.SoT1 + b*normalized_df.SoT90 + c*normalized_df.GSh + c*normalized_df.GxG 
           + a*normalized_df.npGxG + c*normalized_df.Cmp1 + b*normalized_df.AxA + b*normalized_df.KP 
           + b*normalized_df.Third + a*normalized_df.PPA + c*normalized_df.Prog + a*normalized_df.SCA90 
           + a*normalized_df.GCA90 + c*normalized_df.AttPen + c*normalized_df.Succ11 + a*normalized_df.CPA 
           + e*normalized_df.Mis + f*normalized_df.CrdY2 + d*normalized_df.Off) / (7*a + 7*b + 9*c)


df['midfielder'] = (c*normalized_df.Gls + b*normalized_df.Ast + e*normalized_df.CrdY + f*normalized_df.CrdR 
              + b*normalized_df.SoT1 + c*normalized_df.GSoT + c*normalized_df.npGxG + c*normalized_df.Cmp1 
              + b*normalized_df.AxA + c*normalized_df.KP + a*normalized_df.Third + a*normalized_df.PPA 
              + b*normalized_df.Prog + d*normalized_df.Int + d*normalized_df.Blocks + a*normalized_df.SCA90 
              + a*normalized_df.GCA90 + b*normalized_df.Mid3rd + e*normalized_df.Past + c*normalized_df.Succ1 
              + c*normalized_df.Mid3rd11 + b*normalized_df.Succ11 + b*normalized_df.PrgDist + a*normalized_df.CPA
              + f*normalized_df.Mis + e*normalized_df.Dis + f*normalized_df.CrdY2 
              + d*normalized_df.Fls) / (8*a + 10*b + 10*c)

In [16]:
df

,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,Min,...,Opp,Stp,Stp1,OPA,OPA90,AvgDist,goalkeeper,defender,forward,midfielder
44,David Alaba,at AUT,DF,Real_Madrid,La Liga,29,1992.0,30,30,2642,...,0.0,0.0,0.0,0.0,0.0,0.0,0.105263,NaN,NaN,NaN
122,Marco Asensio,es ESP,FW,Real_Madrid,La Liga,26,1996.0,28,16,1461,...,0.0,0.0,0.0,0.0,0.0,0.0,0.036552,NaN,NaN,NaN
168,Gareth Bale,wls WAL,FW,Real_Madrid,La Liga,32,1989.0,5,4,280,...,0.0,0.0,0.0,0.0,0.0,0.0,0.002343,NaN,NaN,NaN
262,Karim Benzema,fr FRA,FW,Real_Madrid,La Liga,34,1987.0,29,29,2398,...,0.0,0.0,0.0,0.0,0.0,0.0,0.056468,NaN,NaN,NaN
292,Blanco,es ESP,MF,Real_Madrid,La Liga,21,2000.0,1,0,31,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000586,NaN,NaN,NaN
403,Eduardo Camavinga,fr FRA,MF,Real_Madrid,La Liga,19,2002.0,21,9,892,...,0.0,0.0,0.0,0.0,0.0,0.0,0.032803,NaN,NaN,NaN
432,Dani Carvajal,es ESP,DF,Real_Madrid,La Liga,30,1992.0,22,16,1434,...,0.0,0.0,0.0,0.0,0.0,0.0,0.056644,NaN,NaN,NaN
435,Casemiro,br BRA,MF,Real_Madrid,La Liga,30,1992.0,28,27,2314,...,0.0,0.0,0.0,0.0,0.0,0.0,0.090033,NaN,NaN,NaN
449,Dani Ceballos,es ESP,MF,Real_Madrid,La Liga,25,1996.0,8,1,138,...,0.0,0.0,0.0,0.0,0.0,0.0,0.006736,NaN,NaN,NaN
944,Peter González,do DOM,DF,Real_Madrid,La Liga,19,2002.0,2,0,11,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000234,NaN,NaN,NaN
1011,Miguel Gutiérrez,es ESP,DF,Real_Madrid,La Liga,20,2001.0,3,3,260,...,0.0,0.0,0.0,0.0,0.0,0.0,0.009431,NaN,NaN,NaN
1043,Eden Hazard,be BEL,FW,Real_Madrid,La Liga,31,1991.0,17,7,690,...,0.0,0.0,0.0,0.0,0.0,0.0,0.020151,NaN,NaN,NaN
1138,Isco,es ESP,MF,Real_Madrid,La Liga,30,1992.0,11,2,216,...,0.0,0.0,0.0,0.0,0.0,0.0,0.011247,NaN,NaN,NaN
1196,Luka Jović,rs SRB,FW,Real_Madrid,La Liga,24,1997.0,13,0,293,...,0.0,0.0,0.0,0.0,0.0,0.0,0.002109,NaN,NaN,NaN
1204,Vinicius Júnior,br BRA,FW,Real_Madrid,La Liga,21,2000.0,31,28,2464,...,0.0,0.0,0.0,0.0,0.0,0.0,0.058284,NaN,NaN,NaN
1318,Toni Kroos,de GER,MF,Real_Madrid,La Liga,32,1990.0,23,22,1854,...,0.0,0.0,0.0,0.0,0.0,0.0,0.103623,NaN,NaN,NaN
1511,Marcelo,br BRA,DF,Real_Madrid,La Liga,33,1988.0,9,3,331,...,0.0,0.0,0.0,0.0,0.0,0.0,0.017690,NaN,NaN,NaN
1523,Mariano,do DOM,FW,Real_Madrid,La Liga,28,1993.0,6,1,173,...,0.0,0.0,0.0,0.0,0.0,0.0,0.001054,NaN,NaN,NaN
1611,Ferland Mendy,fr FRA,DF,Real_Madrid,La Liga,26,1995.0,19,18,1552,...,0.0,0.0,0.0,0.0,0.0,0.0,0.066192,NaN,NaN,NaN
1638,Éder Militão,br BRA,DF,Real_Madrid,La Liga,24,1998.0,31,31,2784,...,0.0,0.0,0.0,0.0,0.0,0.0,0.097531,NaN,NaN,NaN
1661,Luka Modrić,hr CRO,MF,Real_Madrid,La Liga,36,1985.0,24,22,1807,...,0.0,0.0,0.0,0.0,0.0,0.0,0.078259,NaN,NaN,NaN
1732,Nacho,es ESP,DF,Real_Madrid,La Liga,32,1990.0,24,13,1204,...,0.0,0.0,0.0,0.0,0.0,0.0,0.044401,NaN,NaN,NaN
2084,Rodrygo,br BRA,FW,Real_Madrid,La Liga,21,2001.0,27,11,1102,...,0.0,0.0,0.0,0.0,0.0,0.0,0.026008,NaN,NaN,NaN
2177,Sergio Santos,es ESP,DF,Real_Madrid,La Liga,21,2001.0,1,0,11,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,NaN,NaN,NaN
2485,Jesús Vallejo,es ESP,DF,Real_Madrid,La Liga,25,1997.0,1,0,8,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000234,NaN,NaN,NaN
2488,Federico Valverde,uy URU,MF,Real_Madrid,La Liga,23,1998.0,27,17,1621,...,0.0,0.0,0.0,0.0,0.0,0.0,0.053188,NaN,NaN,NaN
2501,Lucas Vázquez,es ESP,DF,Real_Madrid,La Liga,30,1991.0,25,16,1473,...,0.0,0.0,0.0,0.0,0.0,0.0,0.065548,NaN,NaN,NaN
2688,Thibaut Courtois,be BEL,GK,Real_Madrid,La Liga,29,1992.0,33,33,2970,...,1.0,1.0,1.0,1.0,1.0,1.0,0.268781,NaN,NaN,NaN

In [17]:
f_df = df[['Player', 'Pos', 'goalkeeper', 'defender', 'midfielder', 'forward']]

In [18]:
f_str = f_df[['Player', 'Pos']]
f_val = f_df[['goalkeeper', 'defender', 'midfielder', 'forward']]

In [19]:
# f_val = 5 + (((f_val-f_val.min())*(5))/(f_val.max()-f_val.min()))

In [20]:
f_val

      goalkeeper  defender  midfielder  forward
44      0.105263       NaN         NaN      NaN
122     0.036552       NaN         NaN      NaN
168     0.002343       NaN         NaN      NaN
262     0.056468       NaN         NaN      NaN
292     0.000586       NaN         NaN      NaN
403     0.032803       NaN         NaN      NaN
432     0.056644       NaN         NaN      NaN
435     0.090033       NaN         NaN      NaN
449     0.006736       NaN         NaN      NaN
944     0.000234       NaN         NaN      NaN
1011    0.009431       NaN         NaN      NaN
1043    0.020151       NaN         NaN      NaN
1138    0.011247       NaN         NaN      NaN
1196    0.002109       NaN         NaN      NaN
1204    0.058284       NaN         NaN      NaN
1318    0.103623       NaN         NaN      NaN
1511    0.017690       NaN         NaN      NaN
1523    0.001054       NaN         NaN      NaN
1611    0.066192       NaN         NaN      NaN
1638    0.097531       NaN         NaN      NaN
1661    0.078259       NaN         NaN      NaN
1732    0.044401       NaN         NaN      NaN
2084    0.026008       NaN         NaN      NaN
2177    0.000000       NaN         NaN      NaN
2485    0.000234       NaN         NaN      NaN
2488    0.053188       NaN         NaN      NaN
2501    0.065548       NaN         NaN      NaN
2688    0.268781       NaN         NaN      NaN